### ISSUE TITLE
With option --leet  progress calculated  incorrectly

### ISSUE THREAD

**Issue by mfocuz** [mfocuz/DNS_Hunter#1]
Just FYI. Will fix later.

**Comment by lianfeng30** [comment]
perl dns_hunter.pl -h
Experimental keys on scalar is now forbidden at dns_hunter.pl line 234.
Type of arg 1 to keys must be hash or array (not subroutine entry) at dns_hunter.pl line 234, near ");"
Experimental keys on scalar is now forbidden at dns_hunter.pl line 262.
Type of arg 1 to keys must be hash or array (not subroutine entry) at dns_hunter.pl line 262, near ");"
Execution of dns_hunter.pl aborted due to compilation errors.

**Comment by mfocuz** [comment]
lianfeng30 - your issue fixed. Please create new issue in such cases.

**Comment by mfocuz** [comment]
fixed
